VootlaSaiCharan/project-pull-request

- argha.txt
> argha file is commited

- navya
i have created my branch and requesting for pull request
> added biodata

- akhila
I have created a branch called akhila and requesting for pull request
> Added Bio Data 

- poornaf1
i have created the my new poorna branch and sending the pull request accept
> poorna file is added

- roshini.txt
added a file and requesting pull request
> addede roshini.txt file from roshini

- chandan
I have created the my new chandan branch sending the pull request accept
> file added

- sneha.txt
added a file and requesting for pull
> added sneha.txt file from sneha

- mani
> mani file is commited from mani branch

- monikags.txt
Hi monika here please sir accept and approve my pull request
> added my biodata file from monika branch

- Astalakshmi
I added Astalakshmi.txt file into the Astalakshmi   branch in Pull-request-project
> Astalakshmi.txt  file 

- Supriya.txt
I have created a branch called supriya-branch and added a file named Supriya.txt
> added Supriya.txt to Supriya's Remote Repo

- suhas
hi sir suhas here please approve my pull request
> added file

- akash.txt
I create akash branch and add My information
> My Information

- Pravith.txt
> Pravith Gowda

- Aravinth
hi sir Aravinth here  approve my pull request
> add Aravinth file in Aravinth branch

- akash
> details added to akash

- priyanka
I have  created the branch called  priyanka and requesting for full request
> priyanka.txt

- Adarsh
> file is added succesfully

- manisha.txt
i have created my branch and requesting for pull request
> added manisha.txt from master

- poorvika
> my biodata

- hemalatha.txt
I have created new  branch hemalatha and  requesting to pull
> added hemalatha.txt file from hemalatha branch

- jeyashree.txt
i created a one pull request and send to you
> jeyashree.txt

- Monisha.txt
> i added my info into the file

- ujjwal.txt
> added ujjwal.txt from ujjwal

- Nagaveni.txt
>  added my biodate from nagaveni branch
